singleNode: true
xpack.ml.enabled: false
antiAffinity: "soft"
esJavaOpts: "-Xmx700m -Xms700m"
resources:
  requests:
    memory: "100Mi"
    cpu: "10m"
  limits:
    memory: "250Mi"
    cpu: "800m"
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
esConfig:
  elasticsearch.yml: | 
    xpack.ml.enabled: false